### ISSUE TITLE
Parsing numeric values

### ISSUE THREAD

**Issue by tkopecek** [cvt-oss/fb-invoice-pdf-analyzer#4]
It would be nice to have prices in float instead of strings already. I think we can safely assume for now, that everything is in CZK, so storing currency doesn't make much sense.

So, price should look like `{"price": 1234.56}` instead of `{"price":  "1 234.56 Kč"}`.

Does it make sense?

**Comment by agiertli** [comment]
@tkopecek 
solved via https://github.com/cvt-oss/fb-invoice-pdf-analyzer/commit/fc90d65a3a2f3f8bcea3ad240e2b0dc65640db37

Example output:
```
"price": 40.58
...
"totalPaid": 36000.0
```
I will also check with the client whether it's OK to assume to consider only CZK currency. Currently I am not preserving the currency at all.

Can this be closed?

**Comment by tkopecek** [comment]
Yes, thanks!
